In [19]:
#khai báo thư viện
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split#hàm train_test_split để tách bộ dữ liệu,có trong thư viện sklearn

Vi Du ve train_test_split

In [2]:
#khởi tạo  mảng dữ liệu X là 60000 số tự nhiên đầu,y là bình phương của X
X_data=np.arange(60000)
y_data=X_data**2

In [3]:
X_data#hiện X

array([    0,     1,     2, ..., 59997, 59998, 59999])

In [4]:
y_data#hiện y

array([         0,          1,          4, ..., -695327287, -695207292,
       -695087295], dtype=int32)

In [5]:
X_train, X_test,y_train, y_test = train_test_split(X_data,y_data)#tách dữ liệu với các tham số mặc định

In [6]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape#kết quả cho thấy bộ train 75%,test 25%

((45000,), (45000,), (15000,), (15000,))

In [7]:
X_train,X_test

(array([10369, 38608, 44472, ..., 13625, 46010, 43642]),
 array([23970, 28413, 51242, ..., 13778, 21512,   584]))

In [8]:
#tách dữ liệu với các tham số định dạng test 20%,trạng thái state random là 0 
X_train, X_test,y_train, y_test = train_test_split(X_data,y_data,test_size=0.2,random_state=0)

In [9]:
X_train,X_test

(array([ 5778,  5287, 57167, ..., 42613, 43567,  2732]),
 array([ 3048, 19563, 58303, ..., 50430, 21574, 10617]))

In [10]:
#tách dữ liệu với các tham số định dạng test 20%,trạng thái state random là 0,trạng thái lấy không ngẫu nhiên
X_train, X_test,y_train, y_test = train_test_split(X_data,y_data,test_size=0.2,random_state=0,shuffle=False)

In [11]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((48000,), (48000,), (12000,), (12000,))

In [12]:
X_train,X_test

(array([    0,     1,     2, ..., 47997, 47998, 47999]),
 array([48000, 48001, 48002, ..., 59997, 59998, 59999]))

In [13]:
#khởi tạo bộ dữ liệu x,y
x = np.arange(1, 25).reshape(12, 2)
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [14]:
#tách dữ liệu với test 33% trạng thái state random là 0,stratify=y
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0,stratify=y)

In [15]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((8, 2), (4, 2), (8,), (4,))

In [16]:
y_train,y_test

(array([1, 1, 0, 1, 0, 0, 1, 0]), array([0, 1, 1, 0]))

VI DU VE HOI QUY

In [17]:
from sklearn.datasets import load_boston#bộ dữ liệu boston
from sklearn.model_selection import train_test_split#hàm tách dữ liệu

In [20]:
x,y=load_boston(return_X_y=True)#tải dữ liệu

In [30]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=0)#tách bộ dữ liệu train 80%,test 20%

In [31]:
from sklearn.linear_model import LinearRegression#mô hình hồi quy tuyến tính
model=LinearRegression().fit(x_train,y_train)#huấn luyện mô hình

In [32]:
model.score(x_train,y_train)#xác suất dự đoán trên bộ train

0.7730135569264234

In [33]:
model.score(x_test,y_test)#xác suất dự đoán trên bộ test

0.5892223849182507

In [34]:
x_train.shape,x_test.shape#kích thước bộ train vs test

((404, 13), (102, 13))

VI DU VE PHAN LOAI

In [35]:
#khai báo thư viện
from pandas import read_csv
from sklearn.model_selection import train_test_split#tách dữ liệu
from sklearn.ensemble import RandomForestClassifier#mô hình phân loại rừng ngẫu nhiên
from sklearn.metrics import accuracy_score#tính toán hiệu suất mô hình
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/sonar.csv'#link bộ dữ liệu
dataframe = read_csv(url, header=None)#khởi tạo dataFrame bộ dữ liệu sonar.csv
data = dataframe.values
# split into inputs and outputs
X, y = data[:, :-1], data[:, -1]#khởi tạo tính năng,nhãn từ dataframe
print(X.shape, y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)#tách dữ liệu với bộ train 67%
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
model = RandomForestClassifier(random_state=1)#khởi tạo mô hình
model.fit(X_train, y_train)#huấn luyện mô hình
yhat = model.predict(X_test)#khởi tạo mảng chứa kết quả dự đoán
acc = accuracy_score(y_test, yhat)#thông số accuracy của mô hình(sự chính xác mô hình)
print('Accuracy: %.3f' % acc)#in thông số.

(208, 60) (208,)
(139, 60) (69, 60) (139,) (69,)
Accuracy: 0.783
