In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

Vi Du ve train_test_split

In [3]:
X_data=np.arange(60000)
y_data=X_data**2

In [4]:
X_data

array([    0,     1,     2, ..., 59997, 59998, 59999])

In [5]:
y_data

array([         0,          1,          4, ..., -695327287, -695207292,
       -695087295], dtype=int32)

In [10]:
X_train, X_test,y_train, y_test = train_test_split(X_data,y_data)

In [11]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((45000,), (45000,), (15000,), (15000,))

In [12]:
X_train,X_test

(array([ 6868,  5684, 37806, ..., 38652, 49073,  2938]),
 array([24160,  4352, 54930, ..., 31510, 31579, 34961]))

In [6]:
X_train, X_test,y_train, y_test = train_test_split(X_data,y_data,test_size=0.2,random_state=0)

In [9]:
X_train,X_test

(array([33347, 59901, 14702, ..., 58441, 25126, 54980]),
 array([47813, 45052,  4966, ...,  3568, 24955, 27941]))

In [13]:
X_train, X_test,y_train, y_test = train_test_split(X_data,y_data,test_size=0.2,random_state=0,shuffle=False)

In [14]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((48000,), (48000,), (12000,), (12000,))

In [15]:
X_train,X_test

(array([    0,     1,     2, ..., 47997, 47998, 47999]),
 array([48000, 48001, 48002, ..., 59997, 59998, 59999]))

In [16]:
x = np.arange(1, 25).reshape(12, 2)
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0,stratify=y)

In [18]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((8, 2), (4, 2), (8,), (4,))

In [19]:
y_train,y_test

(array([1, 1, 0, 1, 0, 0, 1, 0]), array([0, 1, 1, 0]))

VI DU VE HOI QUY

In [20]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

In [21]:
x,y=load_boston(return_X_y=True)

In [22]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.4, random_state=0)

In [23]:
from sklearn.linear_model import LinearRegression
model=LinearRegression().fit(x_train,y_train)

In [24]:
model.score(x_train,y_train)

0.7668160223286261

In [25]:
model.score(x_test,y_test)

0.6882607142538016

In [27]:
x_train.shape,x_test.shape

((303, 13), (203, 13))

VI DU VE PHAN LOAI

In [28]:
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/sonar.csv'
dataframe = read_csv(url, header=None)
data = dataframe.values
# split into inputs and outputs
X, y = data[:, :-1], data[:, -1]
print(X.shape, y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
model = RandomForestClassifier(random_state=1)
model.fit(X_train, y_train)
yhat = model.predict(X_test)
acc = accuracy_score(y_test, yhat)
print('Accuracy: %.3f' % acc)

(208, 60) (208,)
(139, 60) (69, 60) (139,) (69,)
Accuracy: 0.783
